<script setup>
import { useRouter } from 'vue-router'
import {
  BarChart3,
  Users,
  FolderGit2,
  Zap,
  ArrowRight,
  CheckCircle2,
} from '@lucide/vue'

const router = useRouter()

const features = [
  {
    icon: BarChart3,
    title: 'Repository Analysis',
    description:
      'Get insights on code quality, languages, structure and overall project health.',
  },
  {
    icon: Users,
    title: 'Contributor Insights',
    description:
      'Understand who contributes and how actively the project is maintained.',
  },
  {
    icon: FolderGit2,
    title: 'Issue & PR Summary',
    description:
      'View key trends from issues and pull requests in a simple format.',
  },
  {
    icon: Zap,
    title: 'AI-Powered Insights',
    description:
      'Get a clear, natural language summary of your repository generated by AI.',
  },
]

const steps = [
  {
    number: '1',
    title: 'Enter a GitHub Repository',
    description:
      'Paste the repository URL you want to analyze.',
  },
  {
    number: '2',
    title: 'We Analyze the Data',
    description:
      'We fetch key information and analyze it using advanced AI.',
  },
  {
    number: '3',
    title: 'Get Clear Insights',
    description:
      'View a simple, easy-to-understand summary of the project.',
  },
]

const goToRegister = () => {
  router.push('/register')
}

const goToLogin = () => {
  router.push('/login')
}

const scrollToFeatures = () => {
  document
    .getElementById('features')
    ?.scrollIntoView({ behavior: 'smooth' })
}

const scrollToHowItWorks = () => {
  document
    .getElementById('how-it-works')
    ?.scrollIntoView({ behavior: 'smooth' })
}

const scrollToAbout = () => {
  document
    .getElementById('about')
    ?.scrollIntoView({ behavior: 'smooth' })
}
</script>

<template>
  <div class="min-h-screen bg-[#050b09] text-white overflow-x-hidden">

    <!-- ========================================= -->
    <!-- NAVBAR -->
    <!-- ========================================= -->

    <nav
      class="sticky top-0 z-50 border-b border-white/10 bg-[#050b09]/95 backdrop-blur-md"
    >
      <div
        class="max-w-6xl mx-auto px-6 lg:px-8 h-[70px] flex items-center justify-between"
      >

        <!-- Logo -->
        <button
          @click="router.push('/')"
          class="flex items-center gap-2 group"
        >
          <span
            class="text-2xl font-bold tracking-tight text-white"
          >
            Dev<span class="text-green-400">Lens</span>
          </span>
        </button>

        <!-- Navigation -->
        <div class="hidden md:flex items-center gap-10">
          <button
            @click="scrollToFeatures"
            class="text-sm text-gray-300 hover:text-white transition"
          >
            Features
          </button>

          <button
            @click="scrollToHowItWorks"
            class="text-sm text-gray-300 hover:text-white transition"
          >
            How It Works
          </button>

          <button
            @click="scrollToAbout"
            class="text-sm text-gray-300 hover:text-white transition"
          >
            About
          </button>
        </div>

        <!-- Auth buttons -->
        <div class="flex items-center gap-3">
          <button
            @click="goToLogin"
            class="px-5 py-2.5 rounded-lg border border-green-500/60 text-white text-sm font-medium hover:bg-green-500/10 transition"
          >
            Login
          </button>

          <button
            @click="goToRegister"
            class="px-5 py-2.5 rounded-lg bg-green-400 text-black text-sm font-semibold hover:bg-green-300 transition"
          >
            Sign Up
          </button>
        </div>

      </div>
    </nav>


    <!-- ========================================= -->
    <!-- HERO -->
    <!-- ========================================= -->

    <section
      class="relative border-b border-white/10 overflow-hidden"
    >

      <!-- Green background glow -->
      <div
        class="absolute -top-40 -right-40 w-[500px] h-[500px] rounded-full bg-green-500/10 blur-[130px]"
      ></div>

      <div
        class="absolute top-40 -left-40 w-[350px] h-[350px] rounded-full bg-green-400/5 blur-[110px]"
      ></div>

      <div
        class="relative max-w-6xl mx-auto px-6 lg:px-8 py-24 lg:py-28"
      >

        <div
          class="grid lg:grid-cols-2 gap-16 items-center"
        >

          <!-- Hero text -->
          <div>

            <p
              class="text-sm tracking-[0.2em] uppercase text-green-400 font-medium mb-5"
            >
              Analyze · Understand · Grow
            </p>

            <h1
              class="text-5xl sm:text-6xl lg:text-[64px] leading-[1.05] font-bold tracking-tight"
            >
              Get a clearer

              <span
                class="block text-green-400"
              >
                View of Any
              </span>

              <span
                class="block text-green-400"
              >
                GitHub Project
              </span>
            </h1>

            <p
              class="mt-7 max-w-xl text-lg leading-8 text-gray-400"
            >
              DevLens analyzes GitHub repositories and provides
              a simple, AI-powered summary of code quality,
              contributions, and overall health — so you can
              understand any project in minutes.
            </p>

            <!-- Buttons -->
            <div class="flex flex-wrap gap-4 mt-8">

              <button
                @click="goToRegister"
                class="group px-7 py-3.5 rounded-lg bg-green-400 text-black font-semibold hover:bg-green-300 transition flex items-center gap-2"
              >
                Get Started

                <ArrowRight
                  class="w-5 h-5 group-hover:translate-x-1 transition"
                />
              </button>

              <button
                @click="scrollToHowItWorks"
                class="px-7 py-3.5 rounded-lg border border-green-500/50 text-white font-medium hover:bg-green-500/10 transition"
              >
                Learn More
              </button>

            </div>

          </div>


          <!-- ================================= -->
          <!-- HEALTH PREVIEW CARD -->
          <!-- ================================= -->

          <div class="relative">

            <div
              class="absolute inset-0 bg-green-400/10 blur-3xl rounded-full"
            ></div>

            <div
              class="relative rounded-2xl border border-green-500/40 bg-[#07110d] p-7 shadow-[0_0_60px_rgba(34,197,94,0.08)]"
            >

              <!-- Card heading -->
              <div
                class="flex items-center justify-between pb-5 border-b border-white/10"
              >
                <div class="flex items-center gap-3">
                  <div
                    class="w-3 h-3 rounded-full bg-green-400"
                  ></div>

                  <span
                    class="font-medium text-gray-200"
                  >
                    Repository Health
                  </span>
                </div>

                <span
                  class="text-xs text-gray-500"
                >
                  DevLens Analysis
                </span>
              </div>


              <!-- Metric -->
              <div
                class="py-5 border-b border-white/10"
              >
                <div
                  class="flex items-center justify-between mb-3"
                >
                  <span class="text-gray-200">
                    Code Quality
                  </span>

                  <span class="text-gray-300">
                    85%
                  </span>
                </div>

                <div
                  class="h-2 rounded-full bg-white/10 overflow-hidden"
                >
                  <div
                    class="h-full w-[85%] rounded-full bg-green-400"
                  ></div>
                </div>
              </div>


              <!-- Metric -->
              <div
                class="py-5 border-b border-white/10"
              >
                <div
                  class="flex items-center justify-between mb-3"
                >
                  <span class="text-gray-200">
                    Community Activity
                  </span>

                  <span class="text-gray-300">
                    72%
                  </span>
                </div>

                <div
                  class="h-2 rounded-full bg-white/10 overflow-hidden"
                >
                  <div
                    class="h-full w-[72%] rounded-full bg-green-400"
                  ></div>
                </div>
              </div>


              <!-- Metric -->
              <div
                class="py-5 border-b border-white/10"
              >
                <div
                  class="flex items-center justify-between mb-3"
                >
                  <span class="text-gray-200">
                    Maintainer Support
                  </span>

                  <span class="text-gray-300">
                    90%
                  </span>
                </div>

                <div
                  class="h-2 rounded-full bg-white/10 overflow-hidden"
                >
                  <div
                    class="h-full w-[90%] rounded-full bg-green-400"
                  ></div>
                </div>
              </div>


              <!-- Metric -->
              <div class="pt-5">
                <div
                  class="flex items-center justify-between mb-3"
                >
                  <span class="text-gray-200">
                    Project Health
                  </span>

                  <span class="text-gray-300">
                    82%
                  </span>
                </div>

                <div
                  class="h-2 rounded-full bg-white/10 overflow-hidden"
                >
                  <div
                    class="h-full w-[82%] rounded-full bg-green-400"
                  ></div>
                </div>
              </div>

            </div>

          </div>

        </div>

      </div>
    </section>


    <!-- ========================================= -->
    <!-- FEATURES -->
    <!-- ========================================= -->

    <section
      id="features"
      class="border-b border-white/10"
    >

      <div
        class="max-w-6xl mx-auto px-6 lg:px-8 py-20"
      >

        <div class="mb-12">

          <p
            class="text-sm tracking-[0.2em] uppercase text-green-400 font-medium mb-3"
          >
            Features
          </p>

          <h2
            class="text-4xl md:text-5xl font-bold tracking-tight"
          >
            Everything you need to
            understand a project
          </h2>

        </div>


        <div
          class="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"
        >

          <div
            v-for="feature in features"
            :key="feature.title"
            class="group rounded-xl border border-white/10 bg-[#07100d] p-6 hover:border-green-500/50 hover:bg-[#09150f] transition duration-300"
          >

            <!-- Icon -->
            <div
              class="w-11 h-11 rounded-full border border-green-500/60 flex items-center justify-center mb-6 group-hover:bg-green-400/10 transition"
            >
              <component
                :is="feature.icon"
                class="w-5 h-5 text-green-400"
              />
            </div>

            <h3
              class="text-lg font-semibold mb-3"
            >
              {{ feature.title }}
            </h3>

            <p
              class="text-sm leading-6 text-gray-400"
            >
              {{ feature.description }}
            </p>

          </div>

        </div>

      </div>

    </section>


    <!-- ========================================= -->
    <!-- HOW IT WORKS -->
    <!-- ========================================= -->

    <section
      id="how-it-works"
      class="bg-[#06130d] border-b border-white/10"
    >

      <div
        class="max-w-6xl mx-auto px-6 lg:px-8 py-20"
      >

        <div class="mb-14">

          <p
            class="text-sm tracking-[0.2em] uppercase text-green-400 font-medium mb-3"
          >
            How It Works
          </p>

          <h2
            class="text-4xl md:text-5xl font-bold tracking-tight"
          >
            From repository to insights
            in minutes
          </h2>

        </div>


        <div
          class="grid md:grid-cols-3 gap-10"
        >

          <div
            v-for="(step, index) in steps"
            :key="step.number"
            class="relative"
          >

            <!-- Connecting line -->
            <div
              v-if="index < steps.length - 1"
              class="hidden md:block absolute top-6 left-[calc(50%+40px)] right-[-50%] h-px bg-green-500/50"
            ></div>

            <!-- Number -->
            <div
              class="relative z-10 w-12 h-12 rounded-full border-2 border-green-400 bg-[#06130d] flex items-center justify-center text-green-400 font-semibold mb-6"
            >
              {{ step.number }}
            </div>

            <h3
              class="text-xl font-semibold mb-3"
            >
              {{ step.title }}
            </h3>

            <p
              class="text-gray-400 leading-7 max-w-sm"
            >
              {{ step.description }}
            </p>

          </div>

        </div>

      </div>

    </section>


    <!-- ========================================= -->
    <!-- ABOUT -->
    <!-- ========================================= -->

    <section
      id="about"
      class="border-b border-white/10"
    >

      <div
        class="max-w-6xl mx-auto px-6 lg:px-8 py-20"
      >

        <div class="max-w-3xl">

          <p
            class="text-sm tracking-[0.2em] uppercase text-green-400 font-medium mb-3"
          >
            About
          </p>

          <h2
            class="text-4xl md:text-5xl font-bold mb-7"
          >
            Why we built DevLens
          </h2>

          <p
            class="text-lg leading-8 text-gray-400"
          >
            Open source projects power the modern world,
            but understanding a new repository can be
            overwhelming. DevLens makes it simple by
            providing clear, AI-powered insights, helping
            developers, students, and teams make informed
            decisions.
          </p>

        </div>

      </div>

    </section>


    <!-- ========================================= -->
    <!-- CTA -->
    <!-- ========================================= -->

    <section
      class="relative overflow-hidden"
    >

      <div
        class="absolute inset-0 bg-green-500/[0.03]"
      ></div>

      <div
        class="relative max-w-6xl mx-auto px-6 lg:px-8 py-24 text-center"
      >

        <CheckCircle2
          class="w-10 h-10 text-green-400 mx-auto mb-6"
        />

        <h2
          class="text-4xl md:text-5xl font-bold mb-5"
        >
          Ready to understand your repository?
        </h2>

        <p
          class="text-gray-400 text-lg mb-8"
        >
          Analyze your GitHub project and get clear
          insights in minutes.
        </p>

        <button
          @click="goToRegister"
          class="px-8 py-4 rounded-lg bg-green-400 text-black font-semibold hover:bg-green-300 transition"
        >
          Get Started
        </button>

      </div>

    </section>


    <!-- ========================================= -->
    <!-- FOOTER -->
    <!-- ========================================= -->

    <footer
      class="border-t border-white/10"
    >

      <div
        class="max-w-6xl mx-auto px-6 lg:px-8 py-7 flex flex-col sm:flex-row items-center justify-between gap-4"
      >

        <div
          class="text-lg font-bold"
        >
          Dev<span class="text-green-400">Lens</span>
        </div>

        <p
          class="text-sm text-gray-500"
        >
          © 2026 DevLens. All rights reserved.
        </p>

      </div>

    </footer>

  </div>
</template>